# Winery Project Playground
Messing around with the dataset

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.options.display.max_columns = 25
pd.options.display.max_rows = 100

In [3]:
winery = pd.read_csv("../data/Winery_Data_csv.csv")
winery.columns = winery.columns.str.replace(' ', '')
winery["Date"] = pd.to_datetime(winery["Date"], format="%d-%b-%y")
print(winery.columns)
print(winery.dtypes)

Index(['CustomerID', 'OrderID', 'CustomerSegment', 'Date', 'ZipCode', 'State',
       'Sales2008', 'Sales2009', 'Sales2010', 'SaleAmount', 'Orders2008',
       'Orders2009', 'Orders2010', 'YearAcquired', 'EmailSubscr',
       'NewsletterSubscr', 'Winemakercall', 'EmailSales', 'NewsletterSales',
       'TastingRoomSales', 'WinemakerCallSales'],
      dtype='object')
CustomerID                     int64
OrderID                        int64
CustomerSegment               object
Date                  datetime64[ns]
ZipCode                        int64
State                         object
Sales2008                    float64
Sales2009                    float64
Sales2010                    float64
SaleAmount                   float64
Orders2008                   float64
Orders2009                   float64
Orders2010                   float64
YearAcquired                   int64
EmailSubscr                    int64
NewsletterSubscr               int64
Winemakercall                  int64
EmailSales                   float64
NewsletterSales              float64
TastingRoomSales             float64
WinemakerCallSales           float64
dtype: object

In [4]:
winery.sample(5)

,CustomerID,OrderID,CustomerSegment,Date,ZipCode,State,Sales2008,Sales2009,Sales2010,SaleAmount,Orders2008,Orders2009,Orders2010,YearAcquired,EmailSubscr,NewsletterSubscr,Winemakercall,EmailSales,NewsletterSales,TastingRoomSales,WinemakerCallSales
55753,18181,40928,Casual Visitor,2009-06-09,10004,NY,0.0,57.92,0.00,36.00,0.0,1.0,0.0,2010,1,1,1,0.0,36.0,0.00,0.0
46900,14082,21028,Casual Visitor,2008-11-15,17201,PA,75.0,16.00,0.00,75.00,1.0,1.0,0.0,2008,0,0,0,0.0,0.0,75.00,0.0
61158,20774,19144,Casual Visitor,2008-11-04,89107,NV,0.0,16.00,0.00,47.00,1.0,1.0,0.0,2009,0,0,0,0.0,0.0,47.00,0.0
3323,751,63493,High Roller,2009-11-13,37069,TN,240.0,336.32,228.77,90.82,4.0,4.0,2.0,2010,0,0,0,0.0,0.0,90.82,0.0
30333,7564,54671,Luxury Estate,2009-09-18,20155,VA,74.0,27.43,7.76,6.43,1.0,2.0,1.0,2008,0,0,0,0.0,0.0,6.43,0.0

In [ ]:
winery.loc[:, ["CustomerID", "EmailSubscr", "NewsletterSubscr", "Winemakercall"]].head(50)